<?php
$departments = array(
    "AUS" => array(
        "Linguistics",
        "Bengali",
        "Hindi",
        "Manipuri",
        "Sanskrit",
        "Indian Comparative Literature",
        "Urdu",
        "English",
        "Arabic",
        "French",
        "Economics",
        "Commerce",
        "Computer Center",
        "Central Library",
        "Exam Building",
        "Admin Building",
        "Political Science",
        "History",
        "Sociology",
        "Social Work",
        "Mass Communication",
        "Visual Arts",
        "Performing Arts",
        "Philosophy",
        "Physics",
        "Chemistry",
        "Mathematics",
        "Computer Science",
        "Statistics",
        "Central Instrumentation Laboratory (CIL)",
        "Life Science and Bio-informatics",
        "Microbiology",
        "Biotechnology",
        "Business Administration",
        "Hospitality and Tourism Management",
        "Ecology Environment Science",
        "Agricultural Engineering",
        "Computer Science and Engineering",
        "Electronics and Communication Engineering",
        "Applied Science & Humanities",
        "Pharmaceutical Science",
        "Earth Science",
        "Library & Information Science",
        "Law",
        "Educational Science",
        "Boys Hostel 5",
        "Boys Hostel 4",
        "Boys Hostel 3",
        "Boys Hostel 2",
        "Boys Hostel 1",
        "Girls Hostel 1",
        "Girls Hostel 2",
        "Girls Hostel 3",
        "Girls Hostel 4",
        "Girls Hostel 5",
    ),
    "AUDC" => array(

        "Assamese",
        "Antropology",
        "Commerce",
        "English",
        "Geography",
        "Hindi",
        "History",
        "Life Science",
        "Physics",
        "Political Science",
        "Centre of Tribal Studies"
        // Add more departments for AUDC here as needed
    )
);
